### ISSUE TITLE
DFD Comments - Sept 19

### ISSUE THREAD

**Issue by germonprez** [mjklotz/assignment1ISQA3420#13]
This is looking good. You can always lean towards very descriptive labels. For example: 

package license res 

is better as: 

Request for All Software Package and License Information 

From a development perspective, the second one is a bit stronger for me. 

Matt

**Comment by mjklotz** [comment]
![capture](https://cloud.githubusercontent.com/assets/16803700/18726251/2a25dfdc-8009-11e6-92be-7dff7c51df7a.PNG)

**Comment by germonprez** [comment]
This looks very good. Well done.
